---
#
# Install OVN
#

- hosts: all
  tasks:
    - name: Install leifmadsen/ovs-master copr repo
      get_url:
        url: https://copr.fedorainfracloud.org/coprs/leifmadsen/ovs-master/repo/epel-7/leifmadsen-ovs-master-epel-7.repo
        dest: /etc/yum.repos.d/leifmadsen-ovs-master-epel-7.repo
  become: yes

- hosts: central_group
  tasks:
  - name: Install OVN Central
    yum: name=openvswitch-ovn-central state=latest
  - name: Start OVN northd
    systemd: name=ovn-northd enabled=no state=stopped
  become: yes

- hosts: farm_group
  tasks:
  - name: Install OVN Host
    yum: name=openvswitch-ovn-host state=latest
  - name: Start OVN controller
    systemd: name=ovn-controller enabled=no state=stopped
  become: yes
